### ISSUE TITLE
Moonraker power api not working.

### ISSUE THREAD

**Issue by jeffeb3** [11chrisadams11/Klipper-WS281x_LED_Status#19]
## Versions
moonraker: v0.7.1-876-g87dba2f
Klipper-WS281x_LED_Status: master, `715991aed1a3cbdbbc4c8926028d11e644ad51f8`

## Description

I ran the `klipper_ledstrip.py` from the command line. It exits with this traceback:

```
Traceback (most recent call last):
  File "/home/pi/Klipper-WS281x_LED_Status/./klipper_ledstrip.py", line 167, in <module>
    run()
  File "/home/pi/Klipper-WS281x_LED_Status/./klipper_ledstrip.py", line 110, in run
    if moonraker_api.power_status(moonraker_settings) == 'on':
  File "/home/pi/Klipper-WS281x_LED_Status/moonraker_api.py", line 28, in power_status
    return json.loads(ret.text)['result']['devices'][0]['status']
KeyError: 'result'
```

Navigating to `http://<printer_ip>:7125/machine/device_power/devices` gives me a 404 (in json format, thanks, moonraker). That api call looks correct from [the docs](https://moonraker.readthedocs.io/en/latest/web_api/#get-device-list). Other api calls work (like `http://<printer_ip>:7125/printer/objects/query?heater_bed&extruder&display_status`).

I don't have any power control in my klipper config. I think that may be the reason I am getting different results?

Let me know if I can provide any other info.

## Workaround

I made these changes to get it running here:
```
diff --git a/klipper_ledstrip.py b/klipper_ledstrip.py
index a8d90fc..8ee21f6 100755
--- a/klipper_ledstrip.py
+++ b/klipper_ledstrip.py
@@ -107,7 +107,7 @@ def run():

             if printer_state_ == 'complete':
                 base_temps = []
-                if moonraker_api.power_status(moonraker_settings) == 'on':
+                if completion_settings['shutdown_when_complete'] and moonraker_api.power_status(moonraker_settings) == 'on':
                     shutdown_counter += 1
                     if completion_settings['shutdown_when_complete'] and shutdown_counter > 9:
                         shutdown_counter = 0
```
And in the config:
```
diff --git a/settings.conf b/settings.conf
index 82b68cd..cf3abe5 100644
--- a/settings.conf
+++ b/settings.conf
@@ -9,7 +9,7 @@ strip_settings:
   idle_timeout     : 300     # Time in seconds before LEDs turn off when on same state

 completion_settings:
-  shutdown_when_complete  : True
+  shutdown_when_complete  : False
   bed_temp_for_shutdown   : 50
   hotend_temp_for_shutdown: 40
```
Either the moonraker_api.py should be catching and handling the exception, or that api shouldn't be called at all if `shutdown_if_complete` is false. I understand why you might have added that feature here. But it honestly doesn't fit in with LED control. It might be better to just separate it into a separate project (I sure wish moonraker had a plugin system like octoprint to manage this kind of thing for me, but that is off-topic).

Thanks for all the work. I just got it running 5 mins ago, and I am happy to see it lighting up again after being off since I installed moonraker. I haven't set up the service yet, just running the command through ssh right now.

**Comment by 11chrisadams11** [comment]
Thank you for pointing this out. I guess I need to test all possible setups, not just what I am using.
You are right, the power control should probably not be a part of an LED script. I will see about separating it out into its own project.

**Comment by 11chrisadams11** [comment]
I have removed power control from this script and moved it to another project. If you get a chance to test it out, let me know if it is giving you any errors.

**Comment by jeffeb3** [comment]
I reverted my changes and updated. The new script runs without any of my changes. Thank you!
