### ISSUE TITLE
Script behavior…

### ISSUE THREAD

**Issue by Mikei386** [11chrisadams11/Klipper-WS281x_LED_Status#4]
First of all Thank you! You made it possible to use NeoPixel with Klipper, that’s awesome.

I’m not quite sure if I’m getting this right.
My LEDs are on Pin 10.
When starting the script all LEDs are white. Starting the print job they stay white.
Every 5 minutes or so they change to the expected behavior an showing a green progress bar for about 2 seconds and then changing back to full white.

also when using the macros, the selected mode just stays for 1 or 2 seconds and then it changes to all white again.

Stopping the script and just use the macros, ON, WHITE and PURPLE are working, as well as useing the values in bash.

what am I missing?
Thanks for sour help.

**Comment by 11chrisadams11** [comment]
Thank you for giving it a try. Sorry for the slow reply.

I think the white might be from the progress of the bed heating up. That is the color that is set for BED_HEATING_PROGRESS_COLOR. I am wondering if it is somehow thinking it's still heating but also catching the print progress every so often.

You could verify by changing the BED_HEATING_PROGRESS_COLOR, and see if that is the constant color.

I will look into a better way to tell if the heaters are still heating so it only shows those colors when appropriate.

**Comment by 11chrisadams11** [comment]
@Mikei386 I have made some changes to the logic to hopefully stop it from trying to display both heating and print progress at the same time. Will you try it with the new script and let me know if it helps?

**Comment by Mikei386** [comment]
> @Mikei386 I have made some changes to the logic to hopefully stop it from trying to display both heating and print progress at the same time. Will you try it with the new script and let me know if it helps?

Thanks for your efforts,
I’ll test it as soon as possible.
Currently I’m on vacation.

**Comment by Mikei386** [comment]
Okey I tested it again an after correcting an human error on my side it now works perfectly. Tank you very much.
