### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by NatatorD** [11chrisadams11/Klipper-WS281x_LED_Status#9]
Hi

Firstly, thanks for putting this together, it is REALLY appreciated!

Minor, very minor, typo in your instructions I thought I'd let you know about. You have "chmod 744 ./klipper-ledstrip.py" but it should be "chmod 744 ./klipper_ledstrip.py"

Edit: Had asked a couple of questions as well but then found the Reddit thread so moved questions to there as it seemed a better place to ask.

**Comment by 11chrisadams11** [comment]
That you for letting me know about the typo. I'll get it fixed and pushed up.

I also responded to your question on Reddit. Let me know if you run into any other issues.

**Comment by 11chrisadams11** [comment]
This has been fixed with the latest update. Thanks again for pointing it out.
